Iter9
Yevgeniy-Ten/go-shortener-backend pull request #19
Opened 2024-12-21 17:51 UTC by Yevgeniy-Ten

2024-12-22 08:12 UTC, zhark0vv requested changes

2024-12-22 08:12 UTC, zhark0vv commented on internal/logger/logger.go
> +	//nolint:errcheck // игнорируем ошибку потому что так принято
Ок, но комментари лучше на английском. :)

2024-12-22 08:12 UTC, zhark0vv commented on internal/handlers/json_hander.go
> +	// #second variant
Выбери какой-то один, пожалуйста, а второй удали. :)

2024-12-22 08:12 UTC, zhark0vv commented on shortenertest
Бинари лучше не хранить в репозитории.

2024-12-22 08:12 UTC, zhark0vv commented on cmd/shortener/main.go
>  	r.GET("/ping", func(c *gin.Context) {
Роутинг, даже такой базовый, лучше вынести из main-пакета.

2024-12-22 08:12 UTC, zhark0vv commented on internal/handlers/base_handlers.go
> +	Storage *storage.ShortURLStorage
Лучше, если ты будешь зависеть от интерфейса, а не реализации.

2024-12-22 08:12 UTC, zhark0vv commented on internal/storage/storage.go
> +	if err != nil {
Если что-то пошло не так, нужно обеспечить консистентность данных, а именно, удалить из мапы.

2024-12-22 08:12 UTC, zhark0vv commented on internal/logger/logger.go
> +type MyLogger = *zap.Logger
Рекомендую здесь избавиться от глобального состояния логгера точно так же, как ты избавился от глобального Storage.

Смотри, ты используешь Singleton, у тебя есть один глобальный логгер.
Но в Go это антипаттерн. И причин этому две:

- существование концепции поинтеров
- duck-typing

В Go очень хорошо реализуется классический DI, а отсутствие новых объектов гарантируется поинтерами.
Здесь стоит сделать просто обертку, ее конструктор, создать объект логгера в main-пакете и инжетировать ее туда, где она нужна.

Знаю, что так сделано в учебных материалах.
Пример дан для демонстрации. Обычно мы стараемся избегать глобальных зависимостей.

Рекомендую тебе разобраться детальнее с концепцией Dependency Injection и встроить логгер туда, где он нужен явно.

2024-12-22 08:12 UTC, zhark0vv commented on internal/storage/storage.go
> +	file    *os.File
Если вместо файла, это будет `io.WriteCloser`, backup-storage станет гораздо гибче.
Пусть потребитель решает, где держать бекап.

2024-12-23 07:24 UTC, Yevgeniy-Ten commented on internal/logger/logger.go
> +type MyLogger = *zap.Logger
@zhark0vv я же так и сделал, или как?

я написал чтобы создать мой тип, и в случае замены zap чтобы где я принимаю этот тип rename не делать

type MyLogger = *zap.Logger это создает переменную с сотояние получается?

2024-12-24 11:12 UTC, zhark0vv approved these changes

2024-12-24 11:12 UTC, zhark0vv commented on internal/storage/storage.go
> +	file    io.WriteCloser
Теперь это уже не `file` :)

2024-12-24 11:12 UTC, zhark0vv commented on internal/logger/logger.go
> +type MyLogger = *zap.Logger
А, я понял тебя, действительно, ты прав.
Обертки более принято делать через структуры, анонимно встраивающие другие, не через кастомный тип.

2024-12-24 11:12 UTC, zhark0vv commented on internal/handlers/base_handlers.go
> +type Logger interface {
Мне кажется, логгер можно использовать и по реализации, не абстрагируя его.
Но это опционально.

2024-12-24 11:12 UTC, zhark0vv commented on internal/handlers/base_handlers.go
> +type Storage interface {
Интерфейсы по месту использования лучше делать package-private.

2024-12-24 11:12 UTC, zhark0vv commented on internal/handlers/base_handlers.go
> +		h.Log.Error("Ошибка сохранения URL: ", zap.Error(err))
Тут тоже лучше английский.

2024-12-24 11:12 UTC, zhark0vv commented on internal/handlers/json_hander.go
> +type ShortenRequest struct {
Вспомогательные структуры можно унести в доменный слой приложения.

2024-12-24 11:13 UTC, zhark0vv approved these changes

2024-12-25 12:50 UTC, merged